# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a89cbb2d49a7dce011cf42d9e6d300360039f13115bc42c2312da89e7f8fc212b910084ab71cd4dcd7eadb46a1d215dbd85c92f796589ac00c499a1eda93bdd8

test:
  secret_key_base: cc07875fee25ff7c12f031e85903ccb53b765b80065b39917922ce08a4db3df49bf83d2166b5cd465ab2726c2e2e9957e75e34232c5f66a792e95febc0f176ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
